### PR TITLE
Update Modulefile

### PR DESCRIPTION
**Pull request by fschaer**
modulename incompatible with librarian/puppet module tool

### CODE REVIEW

**Comment by traylenator** [comment]
Hi,
It should be 

CERNOps-vosupport

this is necessary if we upload to puppetforge

Please can you fix the pull request.

Steve.

**Comment by fschaer** [comment]
Ah, sorry I hadn't noticed the case on github. Should be ok now.

**Comment by traylenator** [comment]
For the sake of perfectionism. You can rebase the two commits to one and push -f this.

**Comment by fschaer** [comment]
Hmpff... my first hard reset + push -f in egit, not so easy ;)

**Comment by traylenator** [comment]
Thanks for the patch. 
Perhaps a better way of rebasing and merging those commits is

git rebase -i HEAD^^

will allow to combine the two commits into one and then you git push -f them.

For next time :-)

**Pull request merged**
